### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by MikeTabu** [aNNiMON/Own-Programming-Language-Tutorial#11]
У меня возникла проблема со сборкой программы на вашем языке. На нем вообще можно собрать jar файл? (или любой другой исполняемый файл)

**Comment by aNNiMON** [comment]
Да, есть такая возможность. Необходимо OwnLang.jar открыть как zip архив и закинуть в него скрипт с именем `program.own`, после чего при запуске OwnLang.jar будет запускаться эта программа.
![image](https://github.com/aNNiMON/Own-Programming-Language-Tutorial/assets/1321838/8d4e6f29-967b-4c7e-a7ac-4eebec48e5f2)
Далее jar-файл можно переименовать как заблагорассудится, а для уменьшения размера можно ещё и неиспользуемые модули поудалять в `com/annimon/ownlang/modules/`
![image](https://github.com/aNNiMON/Own-Programming-Language-Tutorial/assets/1321838/982ec30f-982e-4528-a780-2016524b647b)

**Comment by MikeTabu** [comment]
Я имею ввиду, могу ли я собрать свою программу на ownlang в jar файл? То есть сборка программы .own в исполняемый файл .jar

**Comment by aNNiMON** [comment]
Я это и описал выше. Программа program.own в исполняемом jat файле.

**Comment by MikeTabu** [comment]
а можно сделать так, чтобы jar'ник работал независимо от наличия файла programm.own?

**Comment by aNNiMON** [comment]
В какой-то степени да, это будет обычный джарник ownlang. Все команды типа --repl, -f other.own будет работать, если program.own внутри отсутствует.

**Comment by MikeTabu** [comment]
можно с тобой связаться в какой-либо соц сети?
