### ISSUE TITLE
Questions :)

### ISSUE THREAD

**Issue by TheJustLink** [aNNiMON/Own-Programming-Language-Tutorial#2]
1. Куда смотрел, когда делал этот ЯП? (Где изучал)
2. Будет ли байт-код и стэковая машина?
3. Почему забросил видео-уроки и всё пошёл делать в тихаря x) (видимо было интересно это делать, а видео записывать лень?)

**Comment by aNNiMON** [comment]
Привет.
1. Просто смотрел реализации парсера в больших и не очень языках и читал статьи в блогах. Так постепенно сложилось виденье, как всё делать.
2. Это уже отдельно нужно язык делать. Этот был нацелен на то, чтоб рассказать об основах: парсинг, синтаксические конструкции и т.п. 
3. Вроде всё основное рассказал, дальше всё делается схожим образом: придумал синтаксис, реализовал парсинг, создал Expr/Statement и в eval() написал реализацию. Да и большую часть всё же занимает реализация функций в модулях, а это не интересно ни записывать, ни смотреть)
